/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthVerifiedRouteImport } from './routes/auth/verified'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthCheckEmailRouteImport } from './routes/auth/check-email'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExpensesIndexRouteImport } from './routes/_authenticated/expenses/index'
import { Route as AuthOAuthGoogleRouteImport } from './routes/auth/o-auth/google'
import { Route as AuthenticatedExpensesAddRouteImport } from './routes/_authenticated/expenses/add'
import { Route as AuthenticatedExpensesExpenseIdRouteImport } from './routes/_authenticated/expenses/$expenseId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifiedRoute = AuthVerifiedRouteImport.update({
  id: '/auth/verified',
  path: '/auth/verified',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCheckEmailRoute = AuthCheckEmailRouteImport.update({
  id: '/auth/check-email',
  path: '/auth/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpensesIndexRoute =
  AuthenticatedExpensesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExpensesRoute,
  } as any)
const AuthOAuthGoogleRoute = AuthOAuthGoogleRouteImport.update({
  id: '/auth/o-auth/google',
  path: '/auth/o-auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedExpensesAddRoute =
  AuthenticatedExpensesAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => AuthenticatedExpensesRoute,
  } as any)
const AuthenticatedExpensesExpenseIdRoute =
  AuthenticatedExpensesExpenseIdRouteImport.update({
    id: '/$expenseId',
    path: '/$expenseId',
    getParentRoute: () => AuthenticatedExpensesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRouteWithChildren
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/expenses/$expenseId': typeof AuthenticatedExpensesExpenseIdRoute
  '/expenses/add': typeof AuthenticatedExpensesAddRoute
  '/auth/o-auth/google': typeof AuthOAuthGoogleRoute
  '/expenses/': typeof AuthenticatedExpensesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/expenses/$expenseId': typeof AuthenticatedExpensesExpenseIdRoute
  '/expenses/add': typeof AuthenticatedExpensesAddRoute
  '/auth/o-auth/google': typeof AuthOAuthGoogleRoute
  '/expenses': typeof AuthenticatedExpensesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRouteWithChildren
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/_authenticated/expenses/$expenseId': typeof AuthenticatedExpensesExpenseIdRoute
  '/_authenticated/expenses/add': typeof AuthenticatedExpensesAddRoute
  '/auth/o-auth/google': typeof AuthOAuthGoogleRoute
  '/_authenticated/expenses/': typeof AuthenticatedExpensesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/expenses'
    | '/auth/check-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verified'
    | '/auth/verify'
    | '/auth/verify-email'
    | '/expenses/$expenseId'
    | '/expenses/add'
    | '/auth/o-auth/google'
    | '/expenses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/check-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verified'
    | '/auth/verify'
    | '/auth/verify-email'
    | '/expenses/$expenseId'
    | '/expenses/add'
    | '/auth/o-auth/google'
    | '/expenses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/expenses'
    | '/auth/check-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verified'
    | '/auth/verify'
    | '/auth/verify-email'
    | '/_authenticated/expenses/$expenseId'
    | '/_authenticated/expenses/add'
    | '/auth/o-auth/google'
    | '/_authenticated/expenses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthCheckEmailRoute: typeof AuthCheckEmailRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifiedRoute: typeof AuthVerifiedRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthOAuthGoogleRoute: typeof AuthOAuthGoogleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verified': {
      id: '/auth/verified'
      path: '/auth/verified'
      fullPath: '/auth/verified'
      preLoaderRoute: typeof AuthVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/check-email': {
      id: '/auth/check-email'
      path: '/auth/check-email'
      fullPath: '/auth/check-email'
      preLoaderRoute: typeof AuthCheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses/': {
      id: '/_authenticated/expenses/'
      path: '/'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AuthenticatedExpensesIndexRouteImport
      parentRoute: typeof AuthenticatedExpensesRoute
    }
    '/auth/o-auth/google': {
      id: '/auth/o-auth/google'
      path: '/auth/o-auth/google'
      fullPath: '/auth/o-auth/google'
      preLoaderRoute: typeof AuthOAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/expenses/add': {
      id: '/_authenticated/expenses/add'
      path: '/add'
      fullPath: '/expenses/add'
      preLoaderRoute: typeof AuthenticatedExpensesAddRouteImport
      parentRoute: typeof AuthenticatedExpensesRoute
    }
    '/_authenticated/expenses/$expenseId': {
      id: '/_authenticated/expenses/$expenseId'
      path: '/$expenseId'
      fullPath: '/expenses/$expenseId'
      preLoaderRoute: typeof AuthenticatedExpensesExpenseIdRouteImport
      parentRoute: typeof AuthenticatedExpensesRoute
    }
  }
}

interface AuthenticatedExpensesRouteChildren {
  AuthenticatedExpensesExpenseIdRoute: typeof AuthenticatedExpensesExpenseIdRoute
  AuthenticatedExpensesAddRoute: typeof AuthenticatedExpensesAddRoute
  AuthenticatedExpensesIndexRoute: typeof AuthenticatedExpensesIndexRoute
}

const AuthenticatedExpensesRouteChildren: AuthenticatedExpensesRouteChildren = {
  AuthenticatedExpensesExpenseIdRoute: AuthenticatedExpensesExpenseIdRoute,
  AuthenticatedExpensesAddRoute: AuthenticatedExpensesAddRoute,
  AuthenticatedExpensesIndexRoute: AuthenticatedExpensesIndexRoute,
}

const AuthenticatedExpensesRouteWithChildren =
  AuthenticatedExpensesRoute._addFileChildren(
    AuthenticatedExpensesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthCheckEmailRoute: AuthCheckEmailRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifiedRoute: AuthVerifiedRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthOAuthGoogleRoute: AuthOAuthGoogleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
